# Generated by Django 4.0.4 on 2022-05-24 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('f_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('f_image_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('f_ingredients', models.TextField(blank=True, default='', null=True)),
                ('f_sat_fat', models.FloatField(blank=True, default=0, null=True)),
                ('f_trans_fat', models.FloatField(blank=True, default=0, null=True)),
                ('f_mono_fat', models.FloatField(blank=True, default=0, null=True)),
                ('f_poly_fat', models.FloatField(blank=True, default=0, null=True)),
                ('f_chol_fat', models.FloatField(blank=True, default=0, null=True)),
                ('f_fibre', models.FloatField(blank=True, default=0, null=True)),
                ('f_kj', models.FloatField(blank=True, default=0, null=True)),
                ('f_kcal', models.FloatField(blank=True, default=0, null=True)),
                ('f_sodium', models.FloatField(blank=True, default=0, null=True)),
                ('f_protein', models.FloatField(blank=True, default=0, null=True)),
                ('f_carb', models.FloatField(blank=True, default=0, null=True)),
                ('f_sugar', models.FloatField(blank=True, default=0, null=True)),
                ('f_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
