# Generated by Django 4.0.4 on 2022-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centraal', '0002_alter_food_f_owner_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='p_carb',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_chol_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_fibre',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_kcal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_kj',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_mono_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_poly_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_protein',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_sat_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_sodium',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_sugar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_trans_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
