# Generated by Django 4.0.4 on 2022-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centraal', '0003_portion_p_carb_portion_p_chol_fat_portion_p_fibre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='f_total_fat',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='portion',
            name='p_total_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
