# Generated by Django 4.0.4 on 2022-05-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centraal', '0005_alter_food_f_total_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='f_json_dumps',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
